### ISSUE TITLE
ROCm 5.1.1 with PyTorch

### ISSUE THREAD

**Issue by Mikhail42** [ROCm/ROCm#1773] opened 2022-07-23 21:18 UTC
I have:
- Python 3.10
- torch-1.12.0+rocm5.1.1
- torchaudio-0.12.0+rocm5.1.1
- torchvision-0.13.0+rocm5.1.1
- Ubuntu 22.04 LTS
- AMD® Renoir graphics

But when I run any PyTorch function I got 
```
.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from hipGetDeviceCount(). Did you run some cuda functions before calling NumHipDevices() that might have already set an error? Error 101: hipErrorInvalidDevice
```
**Does ROCm support Ubuntu 22.04? Maybe you can suggest something?**

Example of Python code:
```py
   import torch
   cuda = torch.device('cuda')
    y = torch.tensor([1., 2.]).cuda()
```

**Comment by Mikhail42** [comment] 2022-07-23 21:22
PS: found that it is related with:
- https://github.com/RadeonOpenCompute/ROCm/issues/1770

**Comment by aoolmay** [comment] 2022-07-23 21:25
Unfortunately ROCm doesn't support Renoir as far i know. It just isn't supported out of the box and i don't know if hacking is worth the trouble. I can recommend you to try PlaidML which runs just on OpenCL. It's an ML framework based on tensorflow/keras, latest release is from 2020 so it's outdated but it will give you most ML capabilites.

**Comment by JStrbg** [comment] 2022-11-13 17:24
I get this error on RX 6900XT

**Comment by arch-user-france1** [comment] 2023-02-21 15:33
I get it with a RADEON RX 7900XT, too. It may not be related to the "unsupported" GPU!
According to AMD's documentation, any RDNA architecture is supported. Mine is using the new RDNA3.

**Comment by saadrahim** [comment] 2023-02-21 16:27
> I get it with a RADEON RX 7900XT, too. It may not be related to the "unsupported" GPU! According to AMD's documentation, any RDNA architecture is supported. Mine is using the new RDNA3.

Can you please point me to where AMD's documentation states any RDNA architecture is supported?

**Comment by arch-user-france1** [comment] 2023-02-21 18:44
It does not say **any** RDNA architecture is supported, however the documentation is outdated (it should work on kernel 5.15 but that's max 5.3 I think there; but they say it works on 1.15) and I do not know where it is anymore.

Notable, they say **RDNA GPUs are supported** and they list _one_ (only one) rx 6xxx GPU
I'm looking forward to have ROCm working on my system, however currently the developers do not care about documentation, so I guess I'll have to figure out on my own, and if I don't, I'll cry.

My GPU _is_ listed when I issue the command `sudo rocminfo`. So I guess there will be some way...

**Comment by nartmada** [comment] 2024-04-05 23:24
Apologies for not following up.

For the original reported issue, sorry @Mikhail42, Renoir is not a supported GPU.

@arch-user-france1, do you still see this issue with latest ROCm 6.0.2 ?  

Thanks,

**Comment by nartmada** [comment] 2024-04-21 04:04
Closing the ticket.  @arch-user-france1, please re-open if you still see this issue with latest ROCm 6.1.0.  Thanks.

**Closed by nartmada** 2024-04-21 04:04 UTC

**Comment by arch-user-france1** [comment] 2024-04-21 07:17
With 5.7, everything works as intended.
