### ISSUE TITLE
Non-HMM HIP Unit Tests Fail on XNACK+ Systems

### ISSUE THREAD

**Issue by Rmalavally** [ROCm/ROCm#2287] opened 2023-06-28 21:59 UTC
Several non-HMM HIP unit tests, when running on xnack+ memory mode systems, fail. 

This issue is under investigation and will be fixed in a future release.

**Comment by milthorpe** [comment] 2023-10-15 21:32
Is this still an open issue? The [ROCM 5.7.0 Changelog](https://rocm.docs.amd.com/en/latest/CHANGELOG.html#rocm-5-7-0) mentions in Fixed Defects: "Failures observed with non-HMM HIP directed catch2 tests with XNACK+".

**Comment by Rmalavally** [comment] 2023-10-17 20:42
@milthorpe Thank you for reaching out. Yes, this issue is now fixed.

**Comment by tasso** [comment] 2023-12-23 19:04
Closing the issue since it was confirmed fixed on Oct. 17, 2023.

**Closed by tasso** 2023-12-23 19:04 UTC
Labels: Under Investigation, Verified Issue, 5.6.0, Resolved
