### ISSUE TITLE
Could not run 'aten::empty_strided' with arguments from the 'HIP' backend

### ISSUE THREAD

**Issue by ablazet** [ROCm/ROCm#1629] opened 2021-11-26 08:34 UTC
When I ran the resnet50 model on gfx900 device, I found the problem "Could not run 'aten::empty_strided' with arguments from the 'HIP' backend". The version used was  rocm4.2 and pytorch1.10.0，so how should I solve the problem？

**Comment by ROCmSupport** [comment] 2021-11-26 10:19
Thanks @ablazeTang for reaching out.
Can you please share the exact steps(step by step) for better understanding and also to reproduce the problem. 
Please share below outputs also.
_/opt/rocm/bin/rocminfo
/opt/rocm/opencl/bin/clinfo
dmesg_
Thank you.

**Comment by ROCmSupport** [comment] 2022-05-09 05:11
I am closing this as there is no update for the last 6 months.
Request to open new issues, if any, for quick resolutions.
Thank you.

**Comment by randomstuff** [comment] 2022-08-29 09:11
I reached the same problem [when trying to run Stable Diffusion on top of the diffusers package](https://www.gabriel.urdhr.fr/2022/08/28/trying-to-run-stable-diffusion-on-amd-ryzen-5-5600g/) :

> NotImplementedError: Could not run 'aten::empty_strided' with arguments from the 'HIP' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions.

**Comment by randomstuff** [comment] 2022-08-29 10:51
@ablazet For me, this was caused by trying to use the "hip" PyTorch device. [You are expected to use the "cuda" device.](https://pytorch.org/docs/stable/notes/hip.html#hip-interfaces-reuse-the-cuda-interfaces)

**Comment by abhimeda** [comment] 2023-12-20 19:35
@ablazet Is the issue still reproducible with the latest ROCm?  If not, can we please close it?  Thanks!

**Comment by abhimeda** [comment] 2023-12-20 22:07
@ablazet I hope you were able to resolve your issue with this? Can we close this issue?

**Comment by nartmada** [comment] 2024-01-27 04:18
Closing this ticket as there is no update for the last 6 months.  Thanks.

**Closed by nartmada** 2024-01-27 04:18 UTC
