### ISSUE TITLE
ROCm 5.xx ever planning to include GFX1012 navi 14 RDNA GPUs?

### ISSUE THREAD

**Issue by darkar18** [ROCm/ROCm#1735] opened 2022-05-06 16:50 UTC
I know there has been numerous occurrences of issues opened where people having NAVI 14 model (gfx1012) architectures are having trouble using GPU accelerated ML frameworks from last 2 years. I do with all respect believes that it is high time that ROCm team need to work on a built for making High Performance Computing available for RX5500M,RX5500XT,RX5500,RX5600,RX5600XT GPUs

ROCM 5.xx have been successfully installed and built according to manuals but what use does it provide if I cant  use GPU acceleration on Supported versions of pytorch with this?
With the help of ROCm stack, I believe is a platform that was created to bring AMD GPU cards in reply to Nvidia's Dominance in this field.
It is hence so surprising for me to know that ROCm stack supports Nvidia GPUs in ML frameworks but not Native AMD GPUs,
There are many users using RDNA GPUs and it was not a right decision for radeon team to skip RDNA and jump straight to RDNA2/3 cards.
Our trust in you is greatly at stake!!!

**Comment by saadrahim** [comment] 2022-05-17 01:48
I apologize to you in advance. There is no plan to officially add support for gfx1012 in ROCm. 

The only option available for users with Nav1x series GPUs is to build from source. You may get a working solution by building from source. Confirming that the numerical accuracy of the stack is sufficient is left to the end user.

**Comment by darkar18** [comment] 2022-06-02 18:14
Could you attach some manuals or references so that we can try it out ourselves?

**Comment by hanzy1110** [comment] 2022-08-14 15:12
Any guide/resource to build the stack from source?
Thanks!!

**Comment by erkinalp** [comment] 2022-11-13 19:52
Certain parts build unmodified, others build with certain patches applied. See https://github.com/xuhuisheng/rocm-build/tree/master/navi14

**Comment by darkar18** [comment] 2022-11-14 05:36
Hey thanks for resources!
Have you tested it? How about performance and compatibility?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by serhii-nakon** [comment] 2023-05-06 22:35
Hello, you can build OpenCL backend for CPU version of PyTorch from this repository https://github.com/artyom-beilis/pytorch_dlprim , I have tested it and it works with my RX5500M

**Comment by set-soft** [comment] 2023-05-15 00:11
> I apologize to you in advance. There is no plan to officially add support for gfx1012 in ROCm.

Hi @saadrahim! I can understand AMD doesn't have enough resources and/or interest on officially supporting these boards. But we all know that faking the card model makes them usable, the only big annoyance is the lack of a .kdb file with the precompiled kernels. This makes the start-up of things like the Stable Diffusion WebUI to take around 3 minutes in my system. Perhaps some unofficial .kbd files could help people. Just a wish.

**Comment by saadrahim** [comment] 2023-05-15 02:49
Can you let me know what .kdb file you are looking for? I am not familiar with what is missing that is causing your delays. 

I was impressed to see the work behind https://github.com/xuhuisheng/rocm-build/tree/master/navi14.

**Comment by set-soft** [comment] 2023-05-15 09:35
> Can you let me know what .kdb file you are looking for? I am not familiar with what is missing that is causing your delays.

The error message states that I need to install gfx1030_11.kdb, containing precompiled kernels.
For some reason the MIOpen lib included with the PyTorch 1.13.1 doesn't cache anything, I took a look at ~/.cache/miopen and found just an empty dir. 
Not having the precompiled kernels and not having anything cached means that every time I start a fresh docker container the first run of Stable Diffusion WebUI takes 3 to 4 minutes to compile them. Well, that at least the information that all the sources I found explain.
Of course I can't install gfx1030_11.kdb, it doesn't exist, and is even a fake name. I'm forcing **HSA_OVERRIDE_GFX_VERSION=10.3.0** to get unofficial support for Navi 14 (gfx1012). I also think that this is not just a matter of names, I can't take gfx1030_36 data base and rename it to gfx1030_11.
This is why I'm asking if there is a chance to get unofficial (use at your own risk) databases for Navi14.
Note: I'm not using PyTorch 2.x because I get a memory fault, I tried 2.0.0, 2.0.1 and a 2.1.0 nightly. All of them die running `python micro_benchmarking_pytorch.py --network alexnet` (same with Satble Diffusion, but the benchmark is easier to run on a fresh docker image that is half finished).

> I was impressed to see the work behind https://github.com/xuhuisheng/rocm-build/tree/master/navi14.

Thanks, I saw it. I didn't try it yet because compiling the whole ROCm + PyTorch looks like an adventure to me, I need to free an unknown amount of disk space (if the official docker images for ROCm + Pytorch takes 29 GiB I can't even imagine how much disk space I'll need for the code with the debug symbols and repeated at least twice, objects and lib). I have only 16 GiB of RAM and it will use the swap a lot, I have 24 GiB of SDD swap which I guess will do.

**Comment by amayra** [comment] 2023-05-27 01:56
as the owner of RX 5500 xt 8gb this is my first AMD GPU and my last one too 

for stable diffusion and CUDA I'm going with NV GPU in my next upgrade 

I hope AMD thinks more about why its always second place in GPU markets

**Comment by set-soft** [comment] 2023-05-29 10:02
Hi @amayra !
I got the impression that ROCm is aimed at the data center target, not the personal computer segment.
Also looks like AMD doesn't dedicate resources to make it usable for the desktop.
They could use volunteers just giving away some hardware and also dedicate a few people to coordinate enthusiasts, but they don't.
Big corporations usually fail at this, they only see the big numbers, and don't realize that they must have a wider target, after all nobody knows if those users will be the ones that will be making the big buying decisions in the near future.
I also think that they aren't paying attention to boards that will give poor cost to performance ratios, just because these ratios could be used against them. And RX 5500 XT (without half precision floating point support) may be the case.

**Comment by amayra** [comment] 2023-05-30 13:10
> Hi @amayra ! I got the impression that ROCm is aimed at the data center target, not the personal computer segment. Also looks like AMD doesn't dedicate resources to make it usable for the desktop. They could use volunteers just giving away some hardware and also dedicate a few people to coordinate enthusiasts, but they don't. Big corporations usually fail at this, they only see the big numbers, and don't realize that they must have a wider target, after all nobody knows if those users will be the ones that will be making the big buying decisions in the near future. I also think that they aren't paying attention to boards that will give poor cost to performance ratios, just because these ratios could be used against them. And RX 5500 XT (without half precision floating point support) may be the case.

it's sad to see CUDA work for most Nvidia GPU work and even RX 5700 XT is not support here with ROCm

**Comment by serhii-nakon** [comment] 2023-07-23 15:12
Hello, I have just installed Debian 12, and https://packages.debian.org/bookworm/hipcc package then I successfully can use HIP inside Blender for my RX5500M

![Screenshot from 2023-07-23 18-01-04](https://github.com/RadeonOpenCompute/ROCm/assets/57632032/953dc3ab-33e6-40be-8e1c-e8aa5126fa93)
![Screenshot from 2023-07-23 18-10-40](https://github.com/RadeonOpenCompute/ROCm/assets/57632032/f9668d10-6673-4c51-b4aa-9b981fa50da4)

**Comment by serhii-nakon** [comment] 2023-07-23 16:47
Looks like Debian built rocm with support RX5500 by default

**Comment by darkar18** [comment] 2023-07-24 02:10
Thanks a lot for sharing, so does this mean I need to install rocm5.x later after Debian installation or is it out of the box

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by serhii-nakon** [comment] 2023-07-24 07:38
You just need install this https://packages.debian.org/bookworm/hipcc package after install Debian, It install all other packages like dependency. 

Also looks like Arch Linux also provide ROCm with all cards by default.

**Comment by serhii-nakon** [comment] 2023-07-28 14:32
Simple update, by default ROCm very partially support HIP on GFX1012
I just re-compile PyTorch with support GFX1012 and now it require files in while run mnist test and this files not exist for this card.

PS: Looks like this patch return those required files https://github.com/xuhuisheng/rocm-build/blob/master/patch/22.tensile-gfx1012-1.patch

![Screenshot from 2023-07-28 17-32-34](https://github.com/RadeonOpenCompute/ROCm/assets/57632032/5bd82ef2-4841-4184-9346-8471887ec221)

**Comment by serhii-nakon** [comment] 2023-07-28 14:39
Here docker-compose and dockerfile that I used to test
When I will have enough time I will try https://github.com/xuhuisheng/rocm-build - looks like it should work almost fine

[docker.zip](https://github.com/RadeonOpenCompute/ROCm/files/12195542/docker.zip)

**Comment by serhii-nakon** [comment] 2023-07-28 14:59
PSS: I successfully complete this mnist test using this OpenCL backend from this project https://github.com/artyom-beilis/pytorch_dlprim 

Here docker file with PyTorch and this backend 
[docker_cl.zip](https://github.com/RadeonOpenCompute/ROCm/files/12195725/docker_cl.zip)


![Screenshot from 2023-07-28 17-57-14](https://github.com/RadeonOpenCompute/ROCm/assets/57632032/43ab3746-1fce-4a83-972c-7a3df5dacaa6)

**Comment by serhii-nakon** [comment] 2023-08-09 11:11
I successfully re-built ROCm 5.4.3 rccl, rocsparse, rocblas, rocfft, rocrand, PyTorch 2.1 and complete Mnist test using HIP/ROCm

![Screenshot from 2023-08-09 14-11-36](https://github.com/RadeonOpenCompute/ROCm/assets/57632032/ca03eb9c-bdf0-4fe8-a95c-e6cf97a64364)

[Docker_rocm543_Pytorch21git.zip](https://github.com/RadeonOpenCompute/ROCm/files/12301519/Docker_rocm543_Pytorch21git.zip)

**Comment by set-soft** [comment] 2023-08-09 12:31
Hi @serhii-nakon !
Can you upload the docker image to dockerhub or the GitHub registry? This might save a lot of time to other people, specially for people with less than 32 GiB of RAM.

**Comment by serhii-nakon** [comment] 2023-08-09 12:44
Possible I will do it, but need simple refactor to minimize size of container

**Comment by serhii-nakon** [comment] 2023-08-09 14:27
You can use already pre-built Docker image but you can not build with 8GB RAM

**Comment by darkar18** [comment] 2023-08-09 14:43
Will the future versions support build with 8gb ram? Will you guide me if theres anything that I can do

**Comment by serhii-nakon** [comment] 2023-08-09 21:23
I have uploaded this image, please test also PyTorch Audio because I have not enough time to do it (only compiled)
https://hub.docker.com/r/serhiin/rocm_gfx1012_pytorch

**Comment by serhii-nakon** [comment] 2023-08-11 19:37
PS: Sorry for my mistake I added only one tag and it non `latest`, please use this tag `ubuntu2004_rocm543_pytorch21` or full example `serhiin/rocm_gfx1012_pytorch:ubuntu2004_rocm543_pytorch21`

**Comment by serhii-nakon** [comment] 2023-08-11 21:05
I have tested it with diffusers and it works, but sometimes out of memory due 4GB VRAM

**Comment by megumintyan** [comment] 2023-08-22 10:43
@serhii-nakon can you post pytorch .whl files?

**Comment by serhii-nakon** [comment] 2023-08-22 11:17
You can extract it from Docker. But also you need rebuild some part of ROCm (Docker already has it).

Better to use Docker for it where all parts already configured and just work.

**Comment by megumintyan** [comment] 2023-08-22 12:54
@serhii-nakon I can't find it inside the container. Also it takes up 70gb

**Comment by serhii-nakon** [comment] 2023-08-22 15:49
Sorry, I checked and I did not build it.

**Comment by serhii-nakon** [comment] 2023-08-22 18:45
My mistake, I did not build whl files

**Comment by serhii-nakon** [comment] 2023-09-01 16:54
I upload build with Ubuntu 22.04 and minimized size (10GB uncompressed and 2GB compressed size)

**Comment by kernel2008** [comment] 2023-10-01 02:07
> I uploaded build with Ubuntu 22.04 and minimized container/image size (10GB uncompressed and 2GB compressed size) https://hub.docker.com/r/serhiin/rocm_gfx1012_pytorch/tags

@erhii-nakon thinks.When using rocm_gfx1012_pytorch image on the RX5500 device, the gpu device cannot be used by torch

- sudo rocminfo
`Agent 2
  Name:                    gfx1012
  Uuid:                    GPU-XX
  Marketing Name:          AMD Radeon Pro W5500
`
- rocm-smi
`
======================= ROCm System Management Interface =======================
================================= Concise Info =================================
GPU  Temp (DieEdge)  AvgPwr  SCLK  MCLK    Fan     Perf  PwrCap  VRAM%  GPU%
0    36.0c           3.0W    0Mhz  100Mhz  24.71%  auto  105.0W    3%   0%
================================================================================
============================= End of ROCm SMI Log ==============================
`
- pytorch
`
>>> import torch
>>> torch.cuda.is_available()
False
`

**Comment by serhii-nakon** [comment] 2023-10-01 08:54
> > I uploaded build with Ubuntu 22.04 and minimized container/image size (10GB uncompressed and 2GB compressed size) https://hub.docker.com/r/serhiin/rocm_gfx1012_pytorch/tags
> 
> @erhii-nakon thinks.When using rocm_gfx1012_pytorch image on the AMD Radeon Pro W5500 device, the gpu device cannot be used by torch
> 
> - sudo rocminfo
> `Agent 2
>   Name:                    gfx1012
>   Uuid:                    GPU-XX
>   Marketing Name:          AMD Radeon Pro W5500
> `
> - rocm-smi
> `
> ======================= ROCm System Management Interface =======================
> ================================= Concise Info =================================
> GPU  Temp (DieEdge)  AvgPwr  SCLK  MCLK    Fan     Perf  PwrCap  VRAM%  GPU%
> 0    36.0c           3.0W    0Mhz  100Mhz  24.71%  auto  105.0W    3%   0%
> ================================================================================
> ============================= End of ROCm SMI Log ==============================
> `
> - pytorch
> `
> >>> import torch
> >>> torch.cuda.is_available()
> False
> `

Please check permissions inside container like described on page on DockerHub. Also make sure that your provided /dev/dri/* and /dev/kfd devices.

**Comment by serhii-nakon** [comment] 2023-10-01 08:57
Possible you need to upgrade or downgrade kernel or firmwares (I use linux 6.4 and latest amd's firmware). Also make sure that your CPU support atomics (I know that I it required)

**Comment by kernel2008** [comment] 2023-10-04 08:20
> Possible you need to upgrade or downgrade kernel or firmwares (I use linux 6.4 and latest amd's firmware). Also make sure that your CPU support atomics (I know that I it required)

@serhii-nakon Thanks a lot! I can run torch mnist example on radeon pro w5500,but the Debian12 kernel crashes intermittently during execution(python mnist/main.py or other app). The crashes also occur when I set multi-user.target mode.
- hardware
`AMD Ryzen 5 2600+asus b450m+amd radeon pro w5500`
- uname -a
`Linux debma12 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux`
- blender use amd gpu for render ok
- docker run -it --rm --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video --entrypoint /bin/bash serhiin/rocm_gfx1012_pytorch:ubuntu2204_rocm543_pytorch21
`
>>> import torch
>>> torch.cuda.is_available()
True
`

**Comment by serhii-nakon** [comment] 2023-10-04 09:10
@kernel2008 If you have few cards it can cause crashes.

**Comment by fir3-1ce** [comment] 2024-01-09 11:58
Has this been fixed yet? I have Navi14 but `rocminfo` doesn't show any errors. So does that mean it works? OpenCL is still broken on Ubuntu, trying to weigh my options here.

**Comment by cgmb** [comment] 2024-02-14 23:02
Navi 14 is not supported by AMD's official packages, but it is enabled by default in the OS packages for ROCm provided on Debian 13 and Ubuntu 23.10 and later. However, not all libraries provided by ROCm have been packaged for Debian. The libraries available are sufficient to run AI tools like llama-cpp on Navi 14 hardware, but not PyTorch.

**Comment by serhii-nakon** [comment] 2024-03-28 10:21
@cgmb Hello, it almost joke, for really, everyone support almost all AMD cards for ML, but AMD not support it...
I just thinking what better to buy RX7900XTX or pay more and buy some RTX4090 where everything works without problems for years (and I make sure that it for years)

The biggest question I have, how long you will support every card, because Radeon XII supported even for now, but RX5000 (I have it now) not supported officially even in older ROCm (but it technically works I just spend week to investigate how everything build together with gfx101* support).

How I make sure that RX7900XTX not cause the same problem as with RX5000 cards?

PS: I not hate AMD but it really terrible situation with ROCm. I would like to recommend AMD to everyone who want works with ML but at the and I will add that it has problems with supporting it for a long time with some cards (and nobody know how detect which cards will have this problem which no)

**Comment by serhii-nakon** [comment] 2024-03-28 10:36
@cgmb Can you provide how long ROCm team support every card? For example how long RX7900XTX will be supported?

**Comment by cgmb** [comment] 2024-04-02 18:25
> @cgmb Can you provide how long ROCm team support every card? For example how long RX7900XTX will be supported?

Unfortunately, I do not know that myself.

> PS: I want to buy this, but not sure, because worry does RX7900XTX not cause the same problem like with RX5000

Well, there's two things that are different:

1. The RX 7900 XTX has official support for ROCm from AMD, which is something that the RX 5000 series never had. When considering Navi 31 support, I think Navi 21 is a better comparison than Navi 10, 12 or 14.

2. There is a much larger community using ROCm these days. I'm hopeful this will help to prevent regressions beyond AMD's official support cycles. That is partly why I've been helping to build the [Debian ROCm Team's CI system](https://ci.rocm.debian.net/).

Speaking of which, I recently added a Radeon Pro W5700 (gfx1010) worker to the Debian ROCm CI. The results on that worker should be mostly representative of all RDNA 1 hardware, but I do have a Radeon Pro W5500 (gfx1012) that I would like to add. However, I need to either figure out how to get PCIe passthrough working with the W5500 or buy a server dedicated to testing that GPU.

If anyone in the community knows what tricks are needed to get PCIe passthrough working for the W5500, W5700, or MI60 on Debian 12, that may help me to reuse an existing server for testing gfx1012.

**Comment by serhii-nakon** [comment] 2024-04-02 20:04
@cgmb Hello, thank you for your answer very much, I thought that it had official support in past but looks like no.

**Comment by tomasoignons** [comment] 2024-05-01 23:57
> I have uploaded this image, please test also PyTorch Audio because I have not enough time to do it (only compiled) https://hub.docker.com/r/serhiin/rocm_gfx1012_pytorch

I am currently with the RX5500M (inside the Victus 16 laptop), with 16GB of Ram I tried to build PyTorch myself after some compilation problems. It crashed, so I went there after discovering the architecture of the RX5500M. During the lecture I saw this DockerImage, and I hoped it work, because I has no other options

I am on an ArchLinux System, and everything worked fine for me (except when it runned the image the first time (at the installation), it did not detect my GPU, so it made the ML training inside on the CPU, so it tooks some time (like 15-20 min I think)
Then I battled with Docker (mainly because I am a new Linux/Docker user, so I don't know what I am doing LOL), to make it work with Jupyter notebook, and now I have a new Docker Image based on this one (to be honest I don't really know how it works, but it works) where I can create/edit Jupyter notebooks, and when I run them they use the built image of PyTorch and rocm. This Docker image was my last hope to do some ML with PyTorch on my PC, and it works, so thanks a lot.

For other Victus16 users, one information that could be usefull is that with the RX5500M, i needed to put this in the docker-compose if you want the image to detect the GPU: 
    devices:
      - "/dev/kfd"
      - "/dev/dri/card1"
      - "/dev/dri/renderD128"
     (the only thing to change is the card0 to card1, because if you try with card0 well, there is no card0 it will crash).

     If you want to do something with the AMD integrated card (the one integrated with the GPU), first on my PC it didn't work with this Docker Image of PyTorch (it throws some errors), but if you want to try, you need to replace card1 by card2 and renderD128 by renderD129 if I remember well. (but be carefull, while playing with the "normal" version on PyTorch, I installed a tensor on it, and I have to reboot the PC because everything froze, as all the GUI interface is managed on this card + you will just have some errors, and it doesn't make any sense to run anything on this).

**Comment by ppanchad-amd** [comment] 2024-06-17 19:36
@darkar18 Closing ticket as there is no official support of GFX1012 in latest ROCm. Thanks!

**Closed by ppanchad-amd** 2024-06-17 19:36 UTC

**Comment by serhii-nakon** [comment] 2024-06-18 10:20
Technically everyone can use ROCm prebuilt with GFX1010 with any RDNA1 card by using Debian's version of ROCm. I not sure about PyTorch but I think they can also prepare it.

**Comment by TheTrustedComputer** [comment] 2024-08-19 19:05
It's a bummer that users of the RX 5000 cards don't have official ROCm support, but it's not the end of the world. The open-source community can help provide patches to support these cards and extend their life in machine learning applications.

I happen to have one of these cards (an 8GB 5500 XT). I built the latest ROCm release for the gfx1012, and PyTorch and ONNX Runtime work perfectly. However, performance is somewhat lackluster compared to 5.x, likely due to being unoptimized for this hardware, but at least it runs.

**Comment by cgmb** [comment] 2024-08-19 19:10
> @serhii-nakon what about gfx1012? Last time I tried, it was installing fine but throwing weird errors at runtime, as certain parts of ROCm are not available for RDNA 1 at all.

gfx1012 is enabled in the ROCm packages provided in the Debian Trixie 'main' repository and Ubuntu 24.04 'universe' repository.
