### ISSUE TITLE
When running the Windows 11 HIP Installer it tries to install 5.5.0 (Linux) not 5.5.1.

### ISSUE THREAD

**Issue by shott92** [ROCm/ROCm#2377] opened 2023-08-12 13:15 UTC
When running the 
https://www.amd.com/en/developer/rocm-hub/eula/licenses.html?filename=AMD-Software-PRO-Edition-23.Q3-Win10-Win11-For-HIP.exe - AMD-Software-PRO-Edition-23.Q3-Win10-Win11-For-HIP installer - either normally or as adminstrator, it comes up with the offer to install 5.5.0 not the 5.5.1 as described on the page here:
https://www.amd.com/en/developer/rocm-hub/hip-sdk.html

![image](https://github.com/RadeonOpenCompute/ROCm/assets/37227619/18b52a30-15b4-423d-8ab2-928cccf6df3e)

seems to be a bug, could someone advise why this might be, and if there is a solution / work around please?

System version:
![image](https://github.com/RadeonOpenCompute/ROCm/assets/37227619/d1002689-ce13-42ff-9b1b-a56d841f6d9c)

Thanks

**Comment by samathew121** [comment] 2023-08-16 04:56
Hello saadrahim, Pls re-assign this ticked to Balla, Siva narayana in the UI team.

**Comment by kevinroosa** [comment] 2023-09-13 12:12
Adding to this ticket. Documentation for 5.6.1 points to 5.5 installer. Also, is there any clarification on if 5.6.1 is linux-only at the moment (prior to Win release)?

**Comment by bdenhollander** [comment] 2023-09-14 01:35
5.6.1 was announced as [Linux only](https://github.com/RadeonOpenCompute/ROCm/releases/tag/rocm-5.6.1). This page gives a bit more information about future ROCm versioning:
https://rocm.docs.amd.com/en/latest/rocm.html#rocm-release-versioning

**Comment by harkgill-amd** [comment] 2024-07-12 18:44
Hi @shott92, this is not a bug and the installation is working as intended. The version listed at [AMD HIP SDK for Windows](https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html) is the ROCm version which correlates with that specific HIP SDK release. 

For example, the latest HIP SDK (6.1.0) will be installed when you select an installation for ROCm version 6.1.2. Not every Linux point release will have a corresponding SDK release for Windows.

**Closed by harkgill-amd** 2024-07-12 18:44 UTC
Labels: Documentation
