### ISSUE TITLE
amd radeon vii vs vega 64

### ISSUE THREAD

**Issue by SlimRG** [ROCm/ROCm#879] opened 2019-08-28 13:09 UTC
Sorry, If I shouldn't ask here... 
I want to buy GPU only for ROCm PyTorch
So I don't know - what will give me more speed in pytorch

**Comment by kinred** [comment] 2019-08-30 11:17
@himanshugoel2797 the Radeon VII performance increase to a Vega 64, from my experience, is more like 50%.

Also the Radeon VII has useable fp16 support which can further increase the performance, at least for interference jobs.

For example for Resnet 50 training:

Vega 64 fp32:  202 images/s
Vega 64 fp16:  186 images/s ?!?
Radeon VII fp32:  315 images/s
Radeon VII fp16:  455 images/s

(These numbers are with Tensorflow 1.14 though)

So if there is the budget, I would definitely go for a Radeon VII.

**Comment by twuebi** [comment] 2019-09-02 10:33
Be aware of these unresolved issues with the VII, Vega and ROCm:

1. https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/325:
 Networks randomly crash because at least two ops (`tf.transpose`, `tf.dynamic_stitch`) produce garbage integer outputs. Reported in February, confirmed on 5 nodes (3x Radeon VII, 1x Vega FE, 1x unknown), it took 3 months to set up a reproducer and another 3 months to arrive at the conclusion that the problem is most likely somewhere on a "lower level of the stack"

2. https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/534:
BERT, a standard residual FF network in NLP, crashes with a memory access fault. Reported two months ago, confirmed on 3 Radeon VII, the "workaround" is to use the official docker image which means 20% decrease in throughput.

For both errors, there is no fix in sight and no indication of active work or progress on the issue.

**Comment by tasso** [comment] 2023-12-12 22:56
Is this issue still reproducible?  if not, can we please close it?  Thanks!

**Comment by tasso** [comment] 2023-12-18 22:25
Original ticket is more than a year old and the person that opened ticket originally has not responded to the latest request.  If this is still an issue, please file a new ticket and we will happy to investigate it.  Thanks!

**Closed by tasso** 2023-12-18 22:25 UTC
