### ISSUE TITLE
[Issue]: Can't install rocm 6.2.4

### ISSUE THREAD

**Issue by jdchn** [ROCm/ROCm#4022] opened 2024-11-09 19:11 UTC
### Problem Description

The repository InRelease indices for ROCm 6.2.4 appear to be inconsistent with Release artifacts as of 2024-11-09 1900Z. This issue applies to "noble", "focal", and "jammy".

Note — I had to set the ROCm Version field to `ROCm 6.2.3` because there was no option for `ROCm 6.2.4`.

### Operating System

Ubuntu 24.04.1 LTS (Noble Numbat) 

### CPU

N/A

### GPU

N/A

### ROCm Version

ROCm 6.2.3

### Steps to Reproduce

```bash
$ echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.2.4 noble main"     | sudo tee --append /etc/apt/sources.list.d/rocm.list
$ sudo apt update
```

### Additional Information

```bash
$ sudo apt update
...
Get:5 https://repo.radeon.com/rocm/apt/6.2.4 noble/main amd64 Packages [29.6 kB]
Err:5 https://repo.radeon.com/rocm/apt/6.2.4 noble/main amd64 Packages
  File has unexpected size (68560 != 29552). Mirror sync in progress? [IP: 69.192.139.240 443]
  Hashes of expected file:
   - Filesize:29552 [weak]
   - SHA256:5cba5765fe11410ac7a3679e5c8b2eab8c2e294971d8a9e4267c8784b746f21c
   - SHA1:53982ce2011f79dedaf8a5a69c361b8825fea447 [weak]
   - MD5Sum:d55fc8f653990ff0a080cdb20e55fc22 [weak]
  Release file created at: Wed, 06 Nov 2024 18:36:13 +0000
Hit:6 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Fetched 2617 B in 1s (3549 B/s)
Reading package lists... Done
E: Failed to fetch https://repo.radeon.com/rocm/apt/6.2.4/dists/noble/main/binary-amd64/Packages.gz  File has unexpected size (68560 != 29552). Mirror sync in progress? [IP: 69.192.139.240 443]
   Hashes of expected file:
    - Filesize:29552 [weak]
    - SHA256:5cba5765fe11410ac7a3679e5c8b2eab8c2e294971d8a9e4267c8784b746f21c
    - SHA1:53982ce2011f79dedaf8a5a69c361b8825fea447 [weak]
    - MD5Sum:d55fc8f653990ff0a080cdb20e55fc22 [weak]
   Release file created at: Wed, 06 Nov 2024 18:36:13 +0000
```

https://repo.radeon.com/rocm/apt/6.2.4/dists/noble/Release
```text
Origin: repo.radeon.com
Label: repo.radeon.com
Suite: noble
Codename: noble
Version: 6.2.4
Date: Fri, 08 Nov 2024 18:58:55 UTC
Architectures: amd64
Components: main proprietary
Description: ROCm APT Repository
MD5Sum:
 3e929ad7bef77ab769bdcc7cb2e921fe 351040 main/binary-amd64/Packages
 46d07f487bf91c2cb2ab321a7b96178a 68560 main/binary-amd64/Packages.gz
```

https://repo.radeon.com/rocm/apt/6.2.4/dists/noble/InRelease
```text
Origin: repo.radeon.com
Label: repo.radeon.com
Suite: noble
Codename: noble
Version: 6.2.4
Date: Wed, 06 Nov 2024 18:36:13 UTC
Architectures: amd64
Components: main proprietary
Description: ROCm APT Repository
MD5Sum:
 292daa54c9cacecd4d8915fbdee83897 111626 main/binary-amd64/Packages
 d55fc8f653990ff0a080cdb20e55fc22 29552 main/binary-amd64/Packages.gz
```

See also #3980 .

**Comment by johnnynunez** [comment] 2024-11-10 06:45
> ### Problem Description
> The repository InRelease indices for ROCm 6.2.4 appear to be inconsistent with Release artifacts as of 2024-11-09 1900Z. This issue applies to "noble", "focal", and "jammy".
> 
> Note — I had to set the ROCm Version field to `ROCm 6.2.3` because there was no option for `ROCm 6.2.4`.
> 
> ### Operating System
> Ubuntu 24.04.1 LTS (Noble Numbat)
> 
> ### CPU
> N/A
> 
> ### GPU
> N/A
> 
> ### ROCm Version
> ROCm 6.2.3
> 
> ### ROCm Component
> _No response_
> 
> ### Steps to Reproduce
> ```shell
> $ echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/6.2.4 noble main"     | sudo tee --append /etc/apt/sources.list.d/rocm.list
> $ sudo apt update
> ```
> 
> ### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support
> _No response_
> 
> ### Additional Information
> ```shell
> $ sudo apt update
> ...
> Get:5 https://repo.radeon.com/rocm/apt/6.2.4 noble/main amd64 Packages [29.6 kB]
> Err:5 https://repo.radeon.com/rocm/apt/6.2.4 noble/main amd64 Packages
>   File has unexpected size (68560 != 29552). Mirror sync in progress? [IP: 69.192.139.240 443]
>   Hashes of expected file:
>    - Filesize:29552 [weak]
>    - SHA256:5cba5765fe11410ac7a3679e5c8b2eab8c2e294971d8a9e4267c8784b746f21c
>    - SHA1:53982ce2011f79dedaf8a5a69c361b8825fea447 [weak]
>    - MD5Sum:d55fc8f653990ff0a080cdb20e55fc22 [weak]
>   Release file created at: Wed, 06 Nov 2024 18:36:13 +0000
> Hit:6 http://archive.ubuntu.com/ubuntu noble-updates InRelease
> Hit:7 http://archive.ubuntu.com/ubuntu noble-backports InRelease
> Fetched 2617 B in 1s (3549 B/s)
> Reading package lists... Done
> E: Failed to fetch https://repo.radeon.com/rocm/apt/6.2.4/dists/noble/main/binary-amd64/Packages.gz  File has unexpected size (68560 != 29552). Mirror sync in progress? [IP: 69.192.139.240 443]
>    Hashes of expected file:
>     - Filesize:29552 [weak]
>     - SHA256:5cba5765fe11410ac7a3679e5c8b2eab8c2e294971d8a9e4267c8784b746f21c
>     - SHA1:53982ce2011f79dedaf8a5a69c361b8825fea447 [weak]
>     - MD5Sum:d55fc8f653990ff0a080cdb20e55fc22 [weak]
>    Release file created at: Wed, 06 Nov 2024 18:36:13 +0000
> ```
> 
> https://repo.radeon.com/rocm/apt/6.2.4/dists/noble/Release
> 
> ```
> Origin: repo.radeon.com
> Label: repo.radeon.com
> Suite: noble
> Codename: noble
> Version: 6.2.4
> Date: Fri, 08 Nov 2024 18:58:55 UTC
> Architectures: amd64
> Components: main proprietary
> Description: ROCm APT Repository
> MD5Sum:
>  3e929ad7bef77ab769bdcc7cb2e921fe 351040 main/binary-amd64/Packages
>  46d07f487bf91c2cb2ab321a7b96178a 68560 main/binary-amd64/Packages.gz
> ```
> 
> https://repo.radeon.com/rocm/apt/6.2.4/dists/noble/InRelease
> 
> ```
> Origin: repo.radeon.com
> Label: repo.radeon.com
> Suite: noble
> Codename: noble
> Version: 6.2.4
> Date: Wed, 06 Nov 2024 18:36:13 UTC
> Architectures: amd64
> Components: main proprietary
> Description: ROCm APT Repository
> MD5Sum:
>  292daa54c9cacecd4d8915fbdee83897 111626 main/binary-amd64/Packages
>  d55fc8f653990ff0a080cdb20e55fc22 29552 main/binary-amd64/Packages.gz
> ```
> 
> See also #3980 .

For ubuntu 24.04.1
```bash
sudo apt-get remove --purge '^rocm-.*'
sudo apt remove rocm-*
sudo apt purge '*rocm*'
sudo apt update
sudo apt install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"

wget https://repo.radeon.com/amdgpu-install/6.2.4/ubuntu/noble/amdgpu-install_6.2.60204-1_all.deb
sudo apt install ./amdgpu-install_6.2.60204-1_all.deb
sudo amdgpu-install -y --usecase=graphics,rocm

sudo usermod -a -G render,video $LOGNAME # Add the current user to the render and video groups
```

**Comment by HardAndHeavy** [comment] 2024-11-10 08:17
I was experiencing the same problem. When I cleaned everything, I came to the error "Unable to locate package rocm"
![image](https://github.com/user-attachments/assets/c50aead5-9fa2-4e9d-93b2-afa8c0aad533)

The rocm package is also not visible on the [ubuntu packages website](https://packages.ubuntu.com/search?suite=oracular&section=all&arch=any&keywords=rocm&searchon=names)
![image](https://github.com/user-attachments/assets/d1b5e8c8-8273-40a1-b96f-4c26bc7ea8bc)

**Comment by johnnynunez** [comment] 2024-11-10 14:41
> I was experiencing the same problem. When I cleaned everything, I came to the error "Unable to locate package rocm" ![image](https://private-user-images.githubusercontent.com/2789372/384670592-c50aead5-9fa2-4e9d-93b2-afa8c0aad533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDk5MjYsIm5iZiI6MTczMTI0OTYyNiwicGF0aCI6Ii8yNzg5MzcyLzM4NDY3MDU5Mi1jNTBhZWFkNS05ZmEyLTRlOWQtOTNiMi1hZmE4YzBhYWQ1MzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTBUMTQ0MDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDQzYTgxMDRjZDkxMDU3NzYwOGRlN2I5MWU2NWQ4YmNhMzMyYmFmOGFmYTI0YmJiNDYxMTU5MGU5NDM3ZDNhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bI0rprs5TwWChCNNTH7VhOVrCEFhsp4css4nGgPB0k8)
> 
> The rocm package is also not visible on the [ubuntu packages website](https://packages.ubuntu.com/search?suite=oracular&section=all&arch=any&keywords=rocm&searchon=names)

You are using wrong command
sudo amdgpu-install -y --usecase=rocm

**Comment by sofiageo** [comment] 2024-11-10 19:03
It looks to me that someone silently updated the 6.2.4 release and the akamai cache is still serving the old files (until 17 november probably?). Silently updating the files has happened a few more times in the past.

**Comment by HardAndHeavy** [comment] 2024-11-11 07:47
> You are using wrong command sudo amdgpu-install -y --usecase=rocm
Executed all commands in order.
An error appears after the "make" command ` sudo amdgpu-install -y --usecase=graphics,rocm`:
`E: Unable to locate package rocm`
![image](https://github.com/user-attachments/assets/2d518152-47b7-434f-93c0-fc9eab737467)

**Comment by harkgill-amd** [comment] 2024-11-11 15:13
Thanks for the report. There was previously an issue with the ROCm 6.2.3 debian metadata that caused the same `File has unexpected size` error. Will check to see if the root cause is the same again.

@HardAndHeavy, the `Unable to locate package rocm` is due to the rocm repository missing at `/etc/apt/sources.list.d/rocm.list`. A reinstallation of the 6.2.4 amdgpu-install should fix this 
```
sudo amdgpu-install --uninstall --rocmrelease=all
sudo apt purge amdgpu-install
sudo apt autoremove

wget https://repo.radeon.com/amdgpu-install/6.2.4/ubuntu/noble/amdgpu-install_6.2.60204-1_all.deb
sudo apt install ./amdgpu-install_6.2.60204-1_all.deb
sudo apt update
```

**Comment by harkgill-amd** [comment] 2024-11-11 18:36
The file size mismatch issue has been resolved, and I no longer see any errors on my end. @jdchn, @johnnynunez, and @radugrecu97, could you please try running sudo apt update and proceed with the installation?

**Comment by johnnynunez** [comment] 2024-11-11 21:29
> The file size mismatch issue has been resolved, and I no longer see any errors on my end. @jdchn, @johnnynunez, and @radugrecu97, could you please try running sudo apt update and proceed with the installation?

I have no errors.

**Comment by jdchn** [comment] 2024-11-12 01:50
> The file size mismatch issue has been resolved, and I no longer see any errors on my end. @jdchn, @johnnynunez, and @radugrecu97, could you please try running sudo apt update and proceed with the installation?

Looks good to me, now.

**Comment by harkgill-amd** [comment] 2024-11-12 18:31
Thanks everyone! Closing this out.

**Closed by harkgill-amd** 2024-11-12 18:31 UTC
Labels: Under Investigation, ROCm 6.2.3, N/A
