### ISSUE TITLE
Ubuntu 24.04 support

### ISSUE THREAD

**Issue by erkinalp** [ROCm/ROCm#2993] opened 2024-04-02 20:16 UTC
Ubuntu 24.04 is already in its feature freeze. We need time to test, report and fix the bugs to be able to get them fixed right before the release, rather than long after.

**Comment by keryell** [comment] 2024-04-02 20:36
Related to https://github.com/ROCm/ROCm/issues/2939

**Comment by erkinalp** [comment] 2024-04-24 16:13
needs to be handled by AMD per https://bugs.launchpad.net/ubuntu/+bug/2060391

**Comment by supernovae** [comment] 2024-05-13 16:40
This seems rather critical since Ubuntu 22.0.4 has a known issue with 

[ 7813.309408] workqueue: ttm_bo_delayed_delete [amdttm] hogged CPU for >10000us 4 times, consider switching to WQ_UNBOUND

Which is fixed in 23.0.4 (and thus 24.0.4)

https://gitlab.freedesktop.org/drm/amd/-/issues/2282#note_1901512

Right now it's pretty easy to crash any apps using the GPU doing any tensorflow or onyx on ubuntu because of this

**Comment by All3xJ** [comment] 2024-05-13 23:59
Please it would be important for tools like pytorch, hashcat, blender, etc which needs gpu

**Comment by SamuelMarks** [comment] 2024-05-28 18:57
With [amdgpu-install_6.1.60101-1_all.deb](https://repo.radeon.com/amdgpu-install/latest/ubuntu/jammy/amdgpu-install_6.1.60101-1_all.deb) on Ubuntu 24.04 (6.9.2 kernel):
```
$ amdgpu-install --usecase=rocm
[…]
The following packages have unmet dependencies:
 amd-smi-lib : Depends: python3-pip but it is not installable
               Recommends: python3-argcomplete but it is not installable
 hipsolver : Depends: libcholmod3 but it is not installable
             Depends: libsuitesparseconfig5 but it is not installable
 rocm-gdb : Depends: libtinfo5 but it is not installable
            Depends: libncurses5 but it is not installable
            Depends: libpython3.10 but it is not installable or
                     libpython3.8 but it is not installable
 rocm-llvm : Depends: libstdc++-5-dev but it is not installable or
                      libstdc++-7-dev but it is not installable or
                      libstdc++-11-dev but it is not installable
             Depends: libgcc-5-dev but it is not installable or
                      libgcc-7-dev but it is not installable or
                      libgcc-11-dev but it is not installable
             Recommends: gcc-multilib but it is not going to be installed
             Recommends: g++-multilib but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by mikeperalta1** [comment] 2024-06-09 21:23
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hipsolver : Depends: libcholmod3 but it is not installable
             Depends: libsuitesparseconfig5 but it is not installable
 rocm-gdb : Depends: libtinfo5 but it is not installable
            Depends: libncurses5 but it is not installable
            Depends: libpython3.10 but it is not installable or
                     libpython3.8 but it is not installable
E: Unable to correct problems, you have held broken packages.

```

Same :(

**Comment by tangjinchuan** [comment] 2024-06-10 02:18
Try https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/ubuntu.html
or https://github.com/nktice/AMD-AI

**Comment by Stemon8** [comment] 2024-06-10 09:29
> Try https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/ubuntu.html
> or https://github.com/nktice/AMD-AI
> 

This worked for me thank you so much !

**Comment by mikeperalta1** [comment] 2024-06-10 17:15
> Try https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/ubuntu.html or https://github.com/nktice/AMD-AI

This also helped get me to the next step. I now have rocm installed (thank you), but it doesn't seem to have library files for my older AMD GPU:

```
rocBLAS error: Cannot read /opt/rocm/lib/rocblas/library/TensileLibrary.dat: No such file or directory for GPU arch : gfx1032
 List of available TensileLibrary Files : 
"/opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx1101.dat"
"/opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx940.dat"
"/opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx1100.dat"
"/opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx1030.dat"
"/opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx900.dat"
"/opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx908.dat"
"/opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx90a.dat"
"/opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx1102.dat"
"/opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx941.dat"
"/opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx906.dat"
"/opt/rocm/lib/rocblas/library/TensileLibrary_lazy_gfx942.dat"
```

I'm trying to compile llama.cpp if that makes a difference.

**Comment by tangjinchuan** [comment] 2024-06-11 13:27
@mikeperalta1 
List your GPU here with rocminfo or clinfo so that I could see what is going on here. 
If there is no luck with RoCM, I guess you have to try OpenCL route based on clBLAST, which is also a project I helped to tune for speed on llama.cpp.

By the way, I did encounter some hanging behaviour with my 7900XTX Ubuntu 24.04 while selecting any word in the editor of GNU Octave when the .m file is large (I don't know if this is the driver problem). In the meantime, I encountered a WebGPU problem with 7900XTX while no problem on 7800XT (two cards are in two different PCs with different motherboards x570/550 and the same CPU 5700G)

**Comment by TiemenSch** [comment] 2024-06-11 13:34
While it might work for some use cases to add the old PPA's, that is also a great way to brick your system and should not become an advised option at all. There's a good reason these PPA's aren't included as a fallback by default. Please take great caution before undertaking any of the sort.

**Comment by mikeperalta1** [comment] 2024-06-11 21:57
> @mikeperalta1 List your GPU here with rocminfo or clinfo so that I could see what is going on here. If there is no luck with RoCM, I guess you have to try OpenCL route based on clBLAST, which is also a project I helped to tune for speed on llama.cpp.
> 
> By the way, I did encounter some hanging behaviour with my 7900XTX Ubuntu 24.04 while selecting any word in the editor of GNU Octave when the .m file is large (I don't know if this is the driver problem). In the meantime, I encountered a WebGPU problem with 7900XTX while no problem on 7800XT (two cards are in two different PCs with different motherboards x570/550 and the same CPU 5700G)

I ended up using an ENV trick found elsewhere to get the program to run. Basically a var to force an earlier version that supports my card:
```
HSA_OVERRIDE_GFX_VERSION=10.3.0
```

But here's the info in case anyone is interested

```
*******                  
Agent 2                  
*******                  
  Name:                    gfx1032                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon RX 6600 XT              
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      2048(0x800) KB                     
    L3:                      32768(0x8000) KB                   
  Chip ID:                 29695(0x73ff)                      
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2900                               
  BDFID:                   768                                
  Internal Node ID:        1                                  
  Compute Unit:            32                                 
  SIMDs per CU:            2                                  
  Shader Engines:          2                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 118                                
  SDMA engine uCode::      76                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    8372224(0x7fc000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    8372224(0x7fc000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1032         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32
```

**Comment by ppanchad-amd** [comment] 2024-06-20 18:32
@erkinalp Is this ticket still relevant? If not, please close the ticket. Thanks!

**Comment by erkinalp** [comment] 2024-06-20 18:35
Yes, still cannot install.

**Comment by ppanchad-amd** [comment] 2024-06-20 18:41
@erkinalp Did you try https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/native-install/ubuntu.html

**Comment by erkinalp** [comment] 2024-06-20 18:56
@ppanchad-amd 24.04 not listed in that page, and the APT repo also lacks the release definitions for 24.04.

**Comment by ppanchad-amd** [comment] 2024-06-20 19:11
@erkinalp Sorry, 24.04 is not officially supported yet in the lastest ROCm 6.1.2. Thanks!

**Comment by supernovae** [comment] 2024-06-30 19:34
Curious if there is any update.  Ubuntu 22.04 is long in tooth for hardware - we're having to run custom build kernels which break ROCm. Would love to just be modern with 24.04

**Comment by mpettengell** [comment] 2024-07-10 17:25
Is there a timeline on this?

**Comment by Wedge009** [comment] 2024-08-03 00:26
[Documentation for just-released ROCm 6.2.0 lists official support for Ubuntu 24.04](https://rocm.docs.amd.com/en/docs-6.2.0/compatibility/compatibility-matrix.html#past-rocm-compatibility-matrix). I've yet to confirm this, though, especially since support for gfx906 is officially dropped.

**Comment by Anvil5465** [comment] 2024-08-03 00:29
Install instructions [here](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/quick-start.html)

**Comment by harkgill-amd** [comment] 2024-08-06 19:39
Sorry for the wait. Ubuntu 24.04 is now officially supported with the release of ROCm 6.2.0!

**Closed by harkgill-amd** 2024-08-06 19:39 UTC

**Comment by lexchou** [comment] 2024-08-06 23:13
When the latest ROCm 6.2.0 has been installed, almost all GUI applications cannot be opened, here's from the journalctl:

```
Aug 07 07:11:34 dev-ubuntu dbus-daemon[2309]: [session uid=1000 pid=2309] Failed to activate service 'org.freedesktop.portal.Desktop': timed out (service_start_timeout=120000ms)
Aug 07 07:11:34 dev-ubuntu dbus-daemon[2309]: [session uid=1000 pid=2309] Failed to activate service 'org.freedesktop.impl.portal.desktop.gnome': timed out (service_start_timeout=120000ms)
Aug 07 07:12:15 dev-ubuntu dbus-daemon[2309]: [session uid=1000 pid=2309] Activating service name='org.gnome.Nautilus' requested by ':1.85' (uid=1000 pid=3559 comm="gjs /usr/share/gnome-shell/extensions/ding@rasters" label="unconfined")
Aug 07 07:12:15 dev-ubuntu nautilus[10742]: Connecting to org.freedesktop.Tracker3.Miner.Files
Aug 07 07:12:15 dev-ubuntu dbus-daemon[2309]: [session uid=1000 pid=2309] Successfully activated service 'org.gnome.Nautilus'
Aug 07 07:12:15 dev-ubuntu org.gnome.Nautilus[10742]: libEGL warning: DRI2: failed to authenticate
Aug 07 07:12:15 dev-ubuntu org.gnome.Nautilus[10742]: libEGL fatal: DRI driver not from this Mesa build ('24.2.0-devel' vs '24.0.9-0ubuntu0.1')
```

**Comment by chris-hatton** [comment] 2024-11-17 00:08
The Ubuntu 24.04 quick-start install instructions [here](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/quick-start.html) simply don't work, yielding:
```
The following packages have unmet dependencies:
 hipsolver : Depends: libcholmod3 but it is not installable
             Depends: libsuitesparseconfig5 but it is not installable
 rocm-gdb : Depends: libpython3.10 (>= 3.10.0) but it is not installable
 ```
 Is it too much to ask that documenters test the steps they're writing?

**Comment by harkgill-amd** [comment] 2024-11-25 14:55
@chris-hatton, did some more digging and was able to reproduce these exact dependency errors when using the Ubuntu 22.04/jammy amdgpu-install on Ubuntu 24.04/noble. See the difference in the paths for the two installers below.

```
wget https://repo.radeon.com/amdgpu-install/6.2.4/ubuntu/jammy/amdgpu-install_6.2.60204-1_all.deb
```
```
wget https://repo.radeon.com/amdgpu-install/6.2.4/ubuntu/noble/amdgpu-install_6.2.60204-1_all.deb
```
Please be sure to use the correct installer according to the OS that you have installed. As for next steps, you can remove the existing amdgpu-install with the commands from my previous comment and install the 24.04/noble packages with
```
wget https://repo.radeon.com/amdgpu-install/6.2.4/ubuntu/noble/amdgpu-install_6.2.60204-1_all.deb
sudo apt install ./amdgpu-install_6.2.60204-1_all.deb
sudo apt update
sudo apt install amdgpu-dkms rocm
```

**Comment by shoenig** [comment] 2025-01-02 13:45
FYI I ran into the same problem as @chris-hatton because I was following AMD's own tutorial: https://community.amd.com/t5/ai/running-llms-locally-on-amd-gpus-with-ollama/ba-p/713266 (which has you install the outdated version 6.1.3)

```
Depends: libpython3.10 (>= 3.10.0) but it is not installable
```

I realized if you instead browse for and use the latest version of amdgpu-install (as of now, version 6.3.1) the issue is fixed.

https://repo.radeon.com/amdgpu-install/6.3.1/ubuntu/noble/
