### ISSUE TITLE
ROCm 5.1 OpenMP bug (it seems to be a mapping issue)

### ISSUE THREAD

**Issue by jmellorcrummey** [ROCm/ROCm#1725] opened 2022-04-12 20:49 UTC
See attached reproducer. The code crashes. It should not. 

ROCm 5.1
amdclang++

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/3926112/163050255-842b7891-4ff2-45cc-a32a-8a282915816b.png">

 **Details**
 In addition to main, there are two functions that perform OpenMP offloading.

- whole:
  - maps 3 arrays statically declared in the global scope by their names alone
  - computes using these three arrays
- section:
  - maps 3 arrays statically declared in the global scope using either a “to” mapping or a “tofrom” mapping of the form map(to: x[0:nn-1], y[0:nn-1]), map(tofrom: z[0:nn-1])
  - computes using these three arrays

whole runs fine. section crashes.  It is up to the OpenMP compiler and runtime team to figure out what goes wrong with the mappings.

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/3926112/163050690-f836a8de-d727-4fb9-8a49-0b0a95cda939.png">

[rocm-5.1-omp-bug.zip](https://github.com/RadeonOpenCompute/ROCm/files/8476446/rocm-5.1-omp-bug.zip)

**Comment by dhruvachak** [comment] 2022-04-12 22:26
I am able to repro the issue on ROCm5.0.0 and ROCm5.1.0 but not using a recent amd-stg-open compiler. So it is possible that the problem is fixed in the latest bits.

**Comment by dhruvachak** [comment] 2022-04-12 23:46
The code works if an explicit opt-level is added, e.g. -O0, -O1, -O2, and -O3. Here's a compile/run at -O2 with LIBOMPTARGET_KERNEL_TRACE=1 

$ make run
amdclang++ -DIGNORE_BAD_INITIAL_DEVICE -O2 -g -lm -fopenmp -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx90a   -o simple simple.cc
Running simple

time ./simple
calling whole ...
DEVID: 0 SGN:2 ConstWGSize:256  args: 4 teamsXthrds:(   4X  64) reqd:(   4X  64) lds_usage:3008B sgpr_count:108 vgpr_count:122 sgpr_spill_count:0 vgpr_spill_count:0 tripcount:40000000 rpc:1 n:__omp_offloading_fd00_378269f__Z5wholei_l32
calling section ...
DEVID: 0 SGN:2 ConstWGSize:256  args: 4 teamsXthrds:(   4X  64) reqd:(   4X  64) lds_usage:3008B sgpr_count:108 vgpr_count:122 sgpr_spill_count:0 vgpr_spill_count:0 tripcount:40000000 rpc:1 n:__omp_offloading_fd00_378269f__Z7sectioni_l17
0.63user 1.45system 0:02.03elapsed 103%CPU (0avgtext+0avgdata 2786368maxresident)k
0inputs+0outputs (1major+689131minor)pagefaults 0swaps

Compare that when no opt-level is specified. 

$ make run
amdclang++ -DIGNORE_BAD_INITIAL_DEVICE -g -lm -fopenmp -fopenmp-targets=amdgcn-amd-amdhsa -Xopenmp-target=amdgcn-amd-amdhsa -march=gfx90a   -o simple simple.cc
Running simple

time ./simple
calling whole ...
DEVID: 0 SGN:2 ConstWGSize:256  args: 4 teamsXthrds:(   4X  64) reqd:(   4X  64) lds_usage:3048B sgpr_count:83 vgpr_count:124 sgpr_spill_count:0 vgpr_spill_count:0 tripcount:40000000 rpc:1 n:__omp_offloading_fd00_378269f__Z5wholei_l32
calling section ...
DEVID: 0 SGN:2 ConstWGSize:256  args: 4 teamsXthrds:(   4X  64) reqd:(   4X  64) lds_usage:3048B sgpr_count:78 vgpr_count:106 sgpr_spill_count:0 vgpr_spill_count:0 tripcount:40000000 rpc:1 n:__omp_offloading_fd00_378269f__Z7sectioni_l17
Command terminated by signal 6
3.33user 6.15system 0:09.53elapsed 99%CPU (0avgtext+0avgdata 2787152maxresident)k
0inputs+0outputs (1major+923573minor)pagefaults 0swaps
make: *** [Makefile:19: run] Error 134
----------------------------------------------
Notice how the register allocation is different which is unexpected as well, I believe.

**Comment by abhimeda** [comment] 2024-01-25 03:34
@jmellorcrummey  Hi, is your issue resolved in the latest ROCm? If so can we close this ticket?

**Comment by nartmada** [comment] 2024-02-09 04:52
Closing the ticket as no further response from @jmellorcrummey.  Please re-open the ticket if the issue still exists in latest ROCm 6.0.2.  Thanks.

**Closed by nartmada** 2024-02-09 04:52 UTC
