### ISSUE TITLE
[Issue]: Docker image support matrix file fails CI

### ISSUE THREAD

**Issue by danpetreamd** [ROCm/ROCm#2600] opened 2023-10-23 17:18 UTC
### Problem Description

Run rst-lint /home/runner/work/ROCm/ROCm
ERROR [/home/runner/work/ROCm/ROCm/docs/release/docker_image_support_matrix.rst:8](https://github.com/RadeonOpenCompute/ROCm/blob/ce82a047bf98db3c5e71ab98df0c94c784e00440/docs/release/docker_image_support_matrix.rst?plain=1#L8) Unknown directive type "tab-set".
Error: Process completed with exit code 2.

### Operating System

N/A - this is a documentation only issue.

### CPU

N/A - this is a documentation only issue.

### GPU

N/A - this is a documentation only issue.

### ROCm Version

5.7.x

### Steps to Reproduce

Any docs PR will fail with the above error.

### Output of /opt/rocm/bin/rocminfo --support

N/A - this is a documentation only issue.

**Comment by danpetreamd** [comment] 2023-10-23 17:21
https://github.com/RadeonOpenCompute/ROCm/docs/release/docker_image_support_matrix.rst
This file appears to be the only `.rst` file in the /docs/release/ folder.
A possible fix could be converting the `.rst` to `.md`.

**Comment by nartmada** [comment] 2024-01-25 17:45
Hi @danpetreamd, has the issue been fixed?  Can we close this ticket?  Thanks.

**Comment by nartmada** [comment] 2024-01-28 15:50
Closing this ticket as the issue is fixed.

**Closed by nartmada** 2024-01-28 15:50 UTC
